# Generated by Django 4.2.4 on 2023-08-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=6)),
                ('seat_number', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='room_alloment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=10)),
                ('room_number', models.CharField(max_length=6)),
                ('seat_number', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_Number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=4)),
                ('year', models.IntegerField(max_length=1)),
                ('Name', models.IntegerField(max_length=50)),
            ],
        ),
    ]
